name: deploy-code
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-rtluvh --delete'
          options: '--exclude .git'
          ssh_options: ${{secrets.SSH_OPTIONS}}
          src: './'
          dest: ${{secrets.PATH_ONE}}
      - uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-rtluvh --delete'
          options: '--exclude .git'
          ssh_options: ${{secrets.SSH_OPTIONS}}
          src: './'
          dest: ${{secrets.PATH_TWO}}